### ISSUE TITLE
bug in cluster/code/run.py

### ISSUE THREAD

**Issue by xyguo** [aosabook/500lines#137]
line 34 of the file is
```python
Request(node, input, req_done).start()
```
But `cluster.py` doesn't define anything named `Request`, and the program just cannot run. I think it should be `Requester` (defined at line 483 in `cluster.py`).

**Comment by MichaelDiBernardo** [comment]
@djmitche, care to comment?

**Comment by djmitche** [comment]
Hm, `run.py` wasn't really meant to be kept around -- it was just a convenient way to run the code experimentally.  But you're right, with that change it seems to still work!

**Comment by MichaelDiBernardo** [comment]
@xyguo do you want to open a pull request with the `Request -> Requester` change and we'll merge it?

**Comment by MichaelDiBernardo** [comment]
Thanks @djmitche :)

**Comment by MichaelDiBernardo** [comment]
Thank you for your PR @xyguo!
