### ISSUE TITLE
Wrong line count in interpreter

### ISSUE THREAD

**Issue by pdehaye** [aosabook/500lines#163]
"telling us that the LOAD_FAST instruction appears at position zero"
->
"telling us that the LOAD_FAST instruction appears at position six"

No?

**Comment by MichaelDiBernardo** [comment]
Thanks for catching this. I think @akaptur actually meant to use the very first instruction `LOAD_CONST` as the example in this paragraph, so we'll correct it to refer to that instruction instead.

**Comment by pdehaye** [comment]
I think the sixth line would be more instructional, as there are several 0s on that dis.

**Comment by MichaelDiBernardo** [comment]
@pdehaye I think it's probably better to use the first instruction in the list, because it's easier to pick that one as one's eyes move from paragraph to source block. However, I think we should explicitly instruct the reader to look at the first instruction as an example.

**Comment by akaptur** [comment]
LGTM. Thanks @pdehaye for the catch and @MichaelDiBernardo for the fix.
