### ISSUE TITLE
Figures are not showing

### ISSUE THREAD

**Issue by joejean** [aosabook/500lines#166]
The pictures are not loading for the figures in the  [pedometer article ](http://aosabook.org/en/500L/pages/a-pedometer-in-the-real-world.html) and the [clustering by consensus article] (http://aosabook.org/en/500L/pages/clustering-by-consensus.html).
I experienced this issue both on Chrome and Firefox.

**Comment by MichaelDiBernardo** [comment]
Hi,

We mistakenly posted the wrong link for the pedometer article in the blogpost, thanks for catching this. Where did you find that link to the clustering by consensus article, though? 

This is an (embarrassing) artefact of our current build process; the documents at the /pages/ route won't render correctly, you need to remove the 'pages' from the URL to see the final draft of the article. We accidentally hard-linked to this bad copy in the pedometer blogpost.
