### ISSUE TITLE
a Chinese translation of 'interpreter.markdown'

### ISSUE THREAD

**Issue by qingyunha** [aosabook/500lines#168]
Hi, thank you for your hard work. I learned a lot from the chapter "A Python Interpreter Written in Python" and I have translated it into Chinese [here](http://qingyunha.github.io/taotao/), hoping more people can learn from it.

**Comment by MichaelDiBernardo** [comment]
This is amazing! Thank you.

**Comment by qingyunha** [comment]
Thank you.

**Comment by MichaelDiBernardo** [comment]
This has been linked to the corresponding chapter now. Is there a particular place you'd like us to link to when giving credit for the translation?

**Comment by qingyunha** [comment]
No. Don't bother

**Comment by MichaelDiBernardo** [comment]
OK, thank you @qingyunha!
