### ISSUE TITLE
The 99 line link for web spreadsheet not found

### ISSUE THREAD

**Issue by FrankXia0404** [aosabook/500lines#197]
![screen shot 2016-03-02 at 3 10 59 pm](https://cloud.githubusercontent.com/assets/5935836/13479034/1c3eca8e-e089-11e5-9e3a-770a1a26c79a.png)

The link with text "99 line" point to https://github.com/audreyt/500lines/tree/master/spreadsheet/code, which returns 404. 

Should the link be https://github.com/audreyt/500lines/tree/master/spreadsheet instead?

**Comment by MichaelDiBernardo** [comment]
I'll fix this in the next release, thanks. That link should point directly to the 500lines repo, not to the author's fork.

**Comment by MichaelDiBernardo** [comment]
I've decided to remove the links entirely, as they don't make much sense in the context of the print / PDF target.
