### ISSUE TITLE
Em dashes

### ISSUE THREAD

**Issue by dxnn** [aosabook/500lines#203]
Some chapters seem to have correct rendering for em dashes, like http://aosabook.org/en/500L/pages/a-web-crawler-with-asyncio-coroutines.html

Others show '---' instead of '—', like http://aosabook.org/en/500L/dagoba-an-in-memory-graph-database.html and http://aosabook.org/en/500L/pages/a-simple-web-server.html

**Comment by MichaelDiBernardo** [comment]
Apparently our markdown parser doesn't translate `---` into `&mdash;` automatically; one has to literally use `&mdash;` or paste the equivalent character. I'm going to scan for `---` now and replace as necessary.

**Comment by MichaelDiBernardo** [comment]
OK, I think I caught everything in https://github.com/aosabook/500lines/commit/2dd376eb7f8772de88e8e984499ad90fad3a4cf2. Thanks for finding this @dxnn.
