### ISSUE TITLE
Template engine doesn't support else

### ISSUE THREAD

**Issue by itderrickh** [aosabook/500lines#207]
In the template-engine project the markdown states that you can use if else statements, but the code in the template-engine doesn't support it and also none of the test cases test for else statements either.

See markdown file:
[Template Engine Markdown File](https://github.com/aosabook/500lines/blob/master/template-engine/template-engine.markdown)

Search for {% else %} to jump to the issue

**Comment by MichaelDiBernardo** [comment]
Thanks for catching this @itderrickh . I've removed mention of the `{% else %}` tag in the couple of places where it was mentioned throughout the chapter.
