### ISSUE TITLE
Announce official print+web release of 500lines

### ISSUE THREAD

**Issue by hangtwenty** [aosabook/500lines#212]
Hi all,

I am looking forward to when these are released, but I'm unsure how to subscribe to that notification. Right now I'm just "watching" the repo but this is a very noisy way for me to watch. Mail list? meta-issue that I can subscribe to?

Thanks!
Michael

**Comment by hangtwenty** [comment]
I know there is a twitter, and a blog, but I really am hoping for just: "it's done" notification ... I'm sure there are others who feel that way too?

**Comment by MichaelDiBernardo** [comment]
I'll announce it here for you when it's done. I think you should be able to unwatch the repo and just subscribe to this issue, which I think gets you what you're asking for? Others can follow your lead as well, if they like :)

**Comment by goog** [comment]
pdf not included, not convenient

**Comment by MichaelDiBernardo** [comment]
Hi folks, 

"500 Lines" is [available now](http://aosabook.org/blog/2016/07/500-lines-or-less-is-available-now/). Thanks for your patience :) We'll be tweeting the announcement around 2pm ET.
