### ISSUE TITLE
Broken refs to figure 4 in Contingent article

### ISSUE THREAD

**Issue by darius** [aosabook/500lines#217]
At http://aosabook.org/en/500L/contingent-a-fully-dynamic-build-system.html I see these missing bits:

> Refer again to .

> Looking back at , you can see that,

In the markdown file for the chapter at these points are references to a figure 4; there's some kind of web formatting error. Figure 4.4 is itself missing, too.

**Comment by MichaelDiBernardo** [comment]
Thanks -- will take a look!

**Comment by MichaelDiBernardo** [comment]
Fixed in 30a9134 -- thanks again for the report @darius.
