### ISSUE TITLE
URL's to figures are broken

### ISSUE THREAD

**Issue by yutkin** [aosabook/500lines#218]
All URL's to figures in all chapters are broken. For example, http://aosabook.org/en/500L/pages/blockcode-images/blockcode_ide.png

**Comment by MichaelDiBernardo** [comment]
Hi,

Not sure how you're getting to this version (I'm guessing via search engine), but this is a nasty side-effect of our build system at the moment. If you omit the 'pages' part of the URL, you will be at the correct version of the chapter. 

This will go away in a few weeks when we do the final publish for the web version. Sorry for the inconvenience.
