### ISSUE TITLE
Python interpreter won't work with Python 3.6

### ISSUE THREAD

**Issue by serprex** [aosabook/500lines#221]
Python 3.6 is transitioning to a regularized 16-bit wordcode

**Comment by MichaelDiBernardo** [comment]
Thanks for the warning -- we'll make a note of this in the chapter.

**Comment by sicklife** [comment]
[this line](https://github.com/aosabook/500lines/blob/master/crawler/code/crawling.py#L150)  `normalized = urllib.parse.urljoin(response.url, url)` would block the execution in Python 3.6. 

And change it to `normalized = urllib.parse.urljoin(str(response.url), url)` would make it work.
