### ISSUE TITLE
Is this repo still open for including new projects?

### ISSUE THREAD

**Issue by neozhaoliang** [aosabook/500lines#260]
I have written a python project which I think might fit in this repo (<=500 lines of course). But I wonder if this repo is still open for including new projects. Should I add my code and pull a new request?

**Comment by csrgxtu** [comment]
@neozhaoliang  what's your project repo url?

**Comment by neozhaoliang** [comment]
My project is [here](https://github.com/neozhaoliang/pywonderland/tree/master/src/wilson).

It''s a python program that used for making gif animations of the Wilson's algorithm and the DFS algorithm (both are algorithms about graphs). An example image is [here](https://github.com/neozhaoliang/pywonderland/blob/master/img/wilson.gif).

The good thing I think it might be suitable for this repo is that the program is written with pure python: you do not need to install any extra modules to run it (it implements a simple gif encoder), and one can get a vivid animation (usually 200k-500K in size and consists of 2000-4000 frames) in about half one minute. Basically it's a combination of three algorithms: Wilson's algorithm, DFS algorithm and the LZW compression algorithm used in the GIF specification.  I think it shows "what interesting things we can do by reinventing the wheels and in 500 lines or less".

Currently the code is about 600 lines long, that's because I padded many spacing lines and wrote quite detailed comments. It can be easily reformatted to be less than 500 lines.
